### ISSUE TITLE
Chryfi's Snowstorm particle physics roadmap

### ISSUE THREAD

**Issue by Chryfi** [mchorse/blockbuster#172]
My planned features for the snowstorm particle system of Blockbuster mod.
No promises can be made... Minecraft is not designed for physics simulations

- [ ] Implement tangential velocity vector for rotation (only yaw for now)
- [ ] Implement the same thing for every rotation for every body part
- [ ] Implement local velocity from Bedrock Edition
- [ ] Implement OBB collision response
- [ ] Implement angular momentum for OBBs
- [x] Implement Newton's first law of motion for particles lying on a vertical plane
