### ISSUE TITLE
Chryfi's To-Do list

### ISSUE THREAD

**Issue by Chryfi** [mchorse/blockbuster#178]
My planned features for the Blockbuster mod (listed according to priority - however I might do some easy features out of order)
This list only features obvious big (sometimes very complicated) features...
EDIT: I have now a lot of todos for snowstorm and other features, yay....it will never end. This is kind of outdated.

- [x] Exporting a camera path into Blender (Aperture)
- [ ] Copy transformation for aperture
- [x] Implement delete recording command
- [x] Implement recording dupe overwrite parameter
- [x] Implement generalizes deletion confirm screen
- [ ] Implement video decoder for image morph (especially AVI support for transparency)
- [ ] IMPLEMENT THE ANIMATION SYSTEM (maybe)
- [ ] Implement OBB collision system
- [ ] Implement angular momentum for OBB's (probably can't be super realistic due to how the system works)
- [ ] Implement Newton's first law and static friction for obb
- [x] Allow morphs for snowstorm particle system
- [x] Render particles inside body-part editor (could turn out performance heavy)
- [ ] Implement rotation for snowstorm shapes
- [ ] An option which disables (or makes invisible) all particles in the world until minema renders
- [x] Implement Newton's first law of motion for particles lying on a horizontal plane
- [x] Implement local velocity from Bedrock Edition
- [x] Implement tangential velocity vector for rotation (only yaw for now)
- [ ] Implement a folder structure for particles
- [ ] Implement an option for bb gun to make the morph rotate in such a way that it sticks at the block face
- [x] Implement tangential velocity for every rotation for every body part
- [x] Implement local scale

McHorse thinks his mod is "finished"... I will prove him the opposite :)
